ALTER TABLE Jobs ADD COLUMN OwnerWorkerId STRING(128);
ALTER TABLE Jobs ADD COLUMN PreferredWorkerId STRING(128);
ALTER TABLE Jobs ADD COLUMN LeaseExpiresAt TIMESTAMP;
ALTER TABLE Jobs ADD COLUMN LastHeartbeatAt TIMESTAMP;
